# Site
repository: jeremy-hicks/jeremy-hicks.github.io
favicon: images/favicon.ico

# Personal info
name: Jeremy Hicks
title: Security Engineer
email: hello@reysic.com
website: https://reysic.com

darkmode: true

# Social links
# twitter_username: facespics
github_username: jeremy-hicks
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I started my career in IT security after obtaining a B.S. and M.S. in Cognitive Science from UT Dallas. I worked in a Security Operations Center (SOC) for an MSSP monitoring security appliances and performing PCI compliance reporting for about a year before returning to school at SMU Guildhall to pursue a professional certificate in game programming.
  
  Following my graduation from Guildhall, I worked for a startup on a variety of projects, including a multiplayer augmented reality defense-shooter game, automated web application testing via UI and API, and cloud infrastructure codification and deployment of the aforementioned web application. Near the end of my time at the startup I had developed an interest in broader software development (not just games) and how to leverage the cloud. 
  
  I obtained my first AWS certification and then, with a background in security and software development, took on my current role in security engineering.

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: Certifications & Skills
more_content: | # this will include new lines to allow paragraphs
  __Certifications__
   - Microsoft Certified: Azure Security Engineer Associate (May 2020)
   - Microsoft Certified: Azure Fundamentals (Sep 2019)
   - AWS Certified Solutions Architect - Associate (May 2019)
   - Microsoft Technology Associate: Windows Operating System Fundamentals (Jan 2015)
   - Apple Certified Associate - Mac Integration 10.9 (Nov 2014)
   - Microsoft Technology Associate: Security Fundamentals (Nov 2014)
   - CompTIA A+ (Aug 2009)

  __Languages__

  C++, C#, Java, Python, JavaScript, Bash, PowerShell

  __Tools__

  Perforce, Git, Jenkins, AWS CLI/SDK, Azure CLI, Azure DevOps, Terraform, Docker, Ansible, Unity, Unreal

# Projects Section
projects_title: Projects

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
