# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jeremy Hicks
title: Security Engineer
email: hello@reysic.com
website: https://reysic.com

# Social links
# twitter_username: facespics
github_username: jeremy-hicks
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  AWS and Azure certified IT professional with a diverse background of education and experience, including network security, game development, VR/AR, and cloud infrastructure. Characterized by a drive to always be learning and improving. 
  
  Primary areas of professional interest are cloud infrastructure, security, and automation.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Certifications & Skills
more_content: | # this will include new lines to allow paragraphs
  Certifications
   - Microsoft Certified: Azure Fundamentals (Sep 2019)
   - AWS Certified Solutions Architect - Associate (May 2019)
   - Microsoft Technology Associate: Windows Operating System Fundamentals (Jan 2015)
   - Apple Certified Associate - Mac Integration 10.9 (Nov 2014)
   - Microsoft Technology Associate: Security Fundamentals (Nov 2014)
   - CompTIA A+ (Aug 2009)
  Languages
   C++, C#, Java, Python, JavaScript, Bash, PowerShell
  Tools
   Perforce, Git, Jenkins, AWS CLI/SDK, Terraform, Docker, Ansible, Unity, Unreal
  Topics
   -

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
